#!/bin/bash
#
#
#Colors
cyan='\e[0;36m'
green='\e[0;32m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'
blue='\e[1;34m'
#FinishColors
echo -e $red ""
echo "          _       _________ _______ _________ _______  _        _        ";
echo "|\     /|( (    /|\__   __/(  ____ \\__   __/(  ___  )( \      ( \       ";
echo "| )   ( ||  \  ( |   ) (   | (    \/   ) (   | (   ) || (      | (       ";
echo "| |   | ||   \ | |   | |   | (_____    | |   | (___) || |      | |       ";
echo "| |   | || (\ \) |   | |   (_____  )   | |   |  ___  || |      | |       ";
echo "| |   | || | \   |   | |         ) |   | |   | (   ) || |      | |       ";
echo "| (___) || )  \  |___) (___/\____) |   | |   | )   ( || (____/\| (____/\ ";
echo "(_______)|/    )_)\_______/\_______)   )_(   |/     \|(_______/(_______/ ";
                                                                        

echo -e $green +---------------+
echo -e $cyan  { Unistall Tool }
echo -e $green +---------------+
rm -r /usr/share/Dsa.console
echo -e $red { Succesfuly Unistall }
echo -e $blue { DarkSecArmy.Com }
exit                                                              